[general]
use-terminal-pinentry     = true

[hooks]
mail-received = notify-send -a aerc -i mail-unread "[$AERC_ACCOUNT/$AERC_FOLDER] New mail from $AERC_FROM_NAME" "$AERC_SUBJECT"

[compose]
address-book-cmd          = carddav-query -S gmail %s
focus-body                = true
file-picker-cmd           = lf -print-selection %s
reply-to-self             = false
format-flowed             = true

[filters]
text/plain                = colorize
text/calendar             = calendar
message/delivery-status   = colorize
message/rfc822            = colorize
#text/html=pandoc -f html -t plain | colorize
text/html                 = html | colorize
#text/*=bat -fP --file-name="$AERC_FILENAME"
#application/x-sh=bat -fP -l sh
#image/*=catimg -w $(tput cols) -
#subject,~Git(hub|lab)=lolcat -f
#from,thatguywhodoesnothardwraphismessages=wrap -w 100 | colorize
.headers                  = colorize

[ui]
border-char-vertical      = "│"
border-char-horizontal    = "─"
#styleset-name=catppuccin-mocha

column-size               = {{.Size | humanReadable}}
index-columns             = flags:4,size:5,name<20%,subject,date>

[ui:folder=Sent]
column-size               = {{.Size | humanReadable}}
column-recipients         = {{.To | names | join ", "}}{{index (.To | names) 0}}
index-columns             = flags:4,size:5,recipients<20%,subject,date>
