music_directory     "$HOME/music"
playlist_directory  "$XDG_CONFIG_HOME/mpd/playlists"
#pid_file            "$XDG_RUNTIME_DIR/mpd/mpd.pid"
state_file          "$XDG_RUNTIME_DIR/mpd/state"
sticker_file        "$XDG_CACHE_HOME/sticker.sql"
auto_update         "yes"

bind_to_address     "localhost"

input {
        plugin      "curl"
}

audio_output {
        type	      "pipewire"
        name	      "PipeWire Sound Server"
}
